---
- name: craete the user and change the password
  hosts: ansibleYUM
  become: true
  tasks:
    - name: executing tasks under block rescue always
      block:
        - name: creating the user 
          command: "useradd dummy"
  
        - name: set the password
          expect:
             command: passwd dummy
             responses:
                (?i)password: "dummy"
           
      rescue:
          debug:
              msg : error with creating user and setting password

      always:
          debug:
              msg: final always section execution               