---
- name: craete the user and change the password
  hosts: ansibleYUM
  become: true
  tasks:
    # - name: executing tasks under block rescue always
    #   block:
    #     - name: creating the user 
    #       command: "useradd dummy"
  
    #     - name: set the password
    #       expect:
    #          command: passwd dummy
    #          responses:
    #             (?i)password: "dummy"
           
    #   rescue:
    #       debug:
    #           msg : error with creating user and setting password

    #   always:
    #       debug:
    #           msg: final always section execution    
    - name: Handle the error
      block:
        - name: Print a message
          ansible.builtin.debug:
            msg: 'I execute normally'

        - name: Never print this
          ansible.builtin.debug:
            msg: 'I never execute, due to the above task failing, :-('
   
      rescue:
        - name: Print when errors
          ansible.builtin.debug:
             msg: 'I caught an error, can do stuff here to fix it, :-)'           