---
- name: craete the user and change the password
  hosts: ansibleYUM
  become: true
  tasks:
  - name: creating the user 
    command: useradd dummy
  
  - name: set the password
    expect:
      command: passwd dummy
      responses: 
        (?i)password: "dummy"
