---
- name: 
  become: true
  hosts: ansibleYUM
  tasks:
    - name: installing the docker
      yum: 
        name: docker
        state: present
      
    - name: docker service enable    
      service:
        name: docker
        state: started  